[[filter]]
tag   = "builds"
label = "Builds"
nav   = true

[[filter]]
tag   = "simulators"
label = "Simulators"
nav   = true

[[filter]]
tag   = "databases"
label = "Databases"
nav   = true

[[filter]]
tag   = "maps"
label = "Maps"
nav   = true

[[filter]]
tag   = "markets"
label = "Markets"
nav   = true

[[filter]]
tag   = "news"
label = "News"
nav   = true

[[filter]]
tag   = "social"
label = "Social"
nav   = true

[[filter]]
tag   = "wikis"
label = "Wikis"
nav   = true

[[filter]]
tag   = "creators"
label = "Creators"
nav   = true
